name 'workstation-common'
maintainer 'Brian Holtkamp'
maintainer_email 'brholtkamp@gmail.com'
license 'MIT'
description 'Installs all of the OS agnostic files and settings'
long_description 'Handles all OS agnostic files and settings so all nodes are consistent'
version '0.1.0'
source_url 'https://github.com/brholtkamp/workstation-common'
issues_url 'https://github.com/brholtkamp/workstation-common/issues'

depends 'chef-client'
